### ISSUE TITLE
Credentials error from Gradle

### ISSUE THREAD

**Issue by mrpotes** [mark-vieira/gradle-maven-settings-plugin#11]
I can't quite figure out why this is happening, but I get the following error from Gradle:

> You cannot configure authentication schemes for a repository if no credentials are provided

When using this plugin.

I tried debugging the execution, and found that the plugin was being called _after_ Gradle had created the `RepositoryTransport` for the repository (and therefore after the build had already failed).

From invoking with debug and stacktrace options, the full exception is:

```
16:30:10.503 [ERROR] [org.gradle.BuildExceptionReporter] > Could not resolve all dependencies for configuration 'detachedConfiguration3'.
16:30:10.503 [ERROR] [org.gradle.BuildExceptionReporter]    > You cannot configure authentication schemes for a repository if no credentials are provided.
16:30:10.504 [ERROR] [org.gradle.BuildExceptionReporter]
16:30:10.504 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
16:30:10.505 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'amsh'.
16:30:10.505 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
16:30:10.505 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)
16:30:10.505 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
16:30:10.506 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:153)
16:30:10.506 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
16:30:10.506 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
16:30:10.506 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
16:30:10.506 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
16:30:10.506 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:491)
16:30:10.507 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:89)
16:30:10.507 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
16:30:10.507 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
16:30:10.507 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:126)
16:30:10.507 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Factories$1.create(Factories.java:22)
16:30:10.507 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
16:30:10.508 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
16:30:10.508 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:123)
16:30:10.508 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
16:30:10.508 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:100)
16:30:10.508 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:94)
16:30:10.509 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
16:30:10.509 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
16:30:10.509 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:94)
16:30:10.509 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
16:30:10.509 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
16:30:10.509 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
16:30:10.509 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
16:30:10.510 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
16:30:10.510 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
16:30:10.510 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
16:30:10.510 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
16:30:10.510 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
16:30:10.510 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
16:30:10.510 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
16:30:10.511 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
16:30:10.511 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
16:30:10.511 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
16:30:10.511 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
16:30:10.511 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
16:30:10.511 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
16:30:10.511 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
16:30:10.512 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
16:30:10.512 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
16:30:10.512 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:33)
16:30:10.512 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
16:30:10.512 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
16:30:10.512 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
16:30:10.512 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
16:30:10.512 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration 'detachedConfiguration3'.
16:30:10.513 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:70)
16:30:10.513 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolve(ErrorHandlingConfigurationResolver.java:45)
16:30:10.513 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:359)
16:30:10.513 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveNow(DefaultConfiguration.java:334)
16:30:10.513 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:327)
16:30:10.513 [ERROR] [org.gradle.BuildExceptionReporter] 	at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.findExcludedDependencies(ExclusionConfiguringAction.java:115)
16:30:10.513 [ERROR] [org.gradle.BuildExceptionReporter] 	at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.applyMavenExclusions(ExclusionConfiguringAction.java:87)
16:30:10.513 [ERROR] [org.gradle.BuildExceptionReporter] 	at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.execute(ExclusionConfiguringAction.java:81)
16:30:10.514 [ERROR] [org.gradle.BuildExceptionReporter] 	at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.execute(ExclusionConfiguringAction.java:49)
16:30:10.514 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
16:30:10.514 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
16:30:10.514 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
16:30:10.514 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
16:30:10.514 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
16:30:10.514 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
16:30:10.515 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.sun.proxy.$Proxy22.beforeResolve(Unknown Source)
16:30:10.515 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.performPreResolveActions(DefaultConfiguration.java:376)
16:30:10.515 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:357)
16:30:10.515 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveNow(DefaultConfiguration.java:334)
16:30:10.515 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:327)
16:30:10.515 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
16:30:10.515 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:163)
16:30:10.516 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.BeanDynamicObject.getProperty(BeanDynamicObject.java:106)
16:30:10.516 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:81)
16:30:10.516 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
16:30:10.516 [ERROR] [org.gradle.BuildExceptionReporter] 	at build_3dqfakxa5fege5kio9ky2y1e6$_run_closure9_closure22_closure23.doCall(/Users/jamesphillpotts/dev/amsh/build.gradle:119)
16:30:10.525 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
16:30:10.525 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.distribution.internal.DefaultDistribution.contents(DefaultDistribution.java:52)
16:30:10.525 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.distribution.internal.DefaultDistribution_Decorated.contents(Unknown Source)
16:30:10.526 [ERROR] [org.gradle.BuildExceptionReporter] 	at build_3dqfakxa5fege5kio9ky2y1e6$_run_closure9_closure22.doCall(/Users/jamesphillpotts/dev/amsh/build.gradle:118)
16:30:10.526 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
16:30:10.526 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
16:30:10.526 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
16:30:10.526 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$ContainerElementsDynamicObject.invokeMethod(DefaultNamedDomainObjectCollection.java:341)
16:30:10.526 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
16:30:10.526 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
16:30:10.526 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:62)
16:30:10.527 [ERROR] [org.gradle.BuildExceptionReporter] 	at build_3dqfakxa5fege5kio9ky2y1e6$_run_closure9.doCall(/Users/jamesphillpotts/dev/amsh/build.gradle:117)
16:30:10.527 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
16:30:10.527 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
16:30:10.527 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
16:30:10.527 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:68)
16:30:10.527 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:24)
16:30:10.527 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
16:30:10.528 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
16:30:10.528 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
16:30:10.528 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
16:30:10.528 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
16:30:10.528 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
16:30:10.528 [ERROR] [org.gradle.BuildExceptionReporter] 	at build_3dqfakxa5fege5kio9ky2y1e6.run(/Users/jamesphillpotts/dev/amsh/build.gradle:116)
16:30:10.528 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
16:30:10.529 [ERROR] [org.gradle.BuildExceptionReporter] 	... 47 more
16:30:10.529 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.InvalidUserDataException: You cannot configure authentication schemes for a repository if no credentials are provided.
16:30:10.529 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.repositories.transport.RepositoryTransportFactory.validateConnectorFactoryCredentials(RepositoryTransportFactory.java:139)
16:30:10.529 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.repositories.transport.RepositoryTransportFactory.createTransport(RepositoryTransportFactory.java:90)
16:30:10.529 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.repositories.transport.RepositoryTransportFactory.createTransport(RepositoryTransportFactory.java:81)
16:30:10.529 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.getTransport(DefaultMavenArtifactRepository.java:124)
16:30:10.529 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.createResolver(DefaultMavenArtifactRepository.java:111)
16:30:10.530 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.createRealResolver(DefaultMavenArtifactRepository.java:102)
16:30:10.530 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.createResolver(DefaultMavenArtifactRepository.java:93)
16:30:10.530 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ResolveIvyFactory.create(ResolveIvyFactory.java:91)
16:30:10.530 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.createComponentSource(DefaultArtifactDependencyResolver.java:116)
16:30:10.530 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.access$100(DefaultArtifactDependencyResolver.java:58)
16:30:10.530 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver$1.execute(DefaultArtifactDependencyResolver.java:83)
16:30:10.530 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver$1.execute(DefaultArtifactDependencyResolver.java:80)
16:30:10.530 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:137)
16:30:10.531 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:61)
16:30:10.531 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:39)
16:30:10.531 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:80)
16:30:10.531 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:41)
16:30:10.531 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Factories$1.create(Factories.java:22)
16:30:10.531 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:192)
16:30:10.531 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
16:30:10.532 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:106)
16:30:10.532 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:187)
16:30:10.532 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:64)
16:30:10.532 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:39)
16:30:10.532 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolve(DefaultConfigurationResolver.java:91)
16:30:10.532 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyConfigurationResolver.resolve(SelfResolvingDependencyConfigurationResolver.java:40)
16:30:10.533 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolve(ShortCircuitEmptyConfigurationResolver.java:52)
16:30:10.533 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolve(ErrorHandlingConfigurationResolver.java:43)
16:30:10.533 [ERROR] [org.gradle.BuildExceptionReporter] 	... 96 more
```

**Comment by mark-vieira** [comment]
Are you by any chance configuring a repository with a custom auth scheme?

https://docs.gradle.org/current/userguide/repository_types.html#sub:authentication_schemes
