### ISSUE TITLE
Plugin does not work anymore in gradle 8.2

### ISSUE THREAD

**Issue by andybdahl** [mark-vieira/gradle-maven-settings-plugin#29]
It seems bumping to gradle 8.2 now breaks because of this settings plugin.
Here is the error stacktrace coming from gradle:

```
FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Plugin 'net.linguica.maven-settings': external process started 'env'
  See https://docs.gradle.org/8.2/userguide/configuration_cache.html#config_cache:requirements:external_processes

See the complete report at file:///Users/runner/work/1/s/build/reports/configuration-cache/bf5990qu3jevy8o8crnmpt4x7/8vbc41lcq8gwzfj2h91grztxz/configuration-cache-report.html
> Starting an external process 'env' during configuration time is unsupported.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org./

BUILD FAILED in 8m

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
76 actionable tasks: 76 executed
Configuration cache entry discarded with 1 problem.
Error: The process '/Users/runner/work/1/s/gradlew' failed with exit code 1
    at ExecState._setResult (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.231.0/node_modules/azure-pipelines-task-lib/toolrunner.js:943:25)
    at ExecState.CheckComplete (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.231.0/node_modules/azure-pipelines-task-lib/toolrunner.js:926:18)
    at ChildProcess.<anonymous> (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.231.0/node_modules/azure-pipelines-task-lib/toolrunner.js:839:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
##[error]Error: The process '/Users/runner/work/1/s/gradlew' failed with exit code 1
Finishing: Assemble and run unit tests (:tv:app module)```

**Comment by andybdahl** [comment]
@mark-vieira @aalmiray can you check this issue? it is a major issue because AZ Artifacts recommends this plugin in their official documentaion and this now does not work with gradle 8.2

**Comment by aalmiray** [comment]
Sorry, I have nothing to do with this plugin.

**Comment by andybdahl** [comment]
@mark-vieira any news on this issue?

**Comment by rmanibus** [comment]
I created a new version of this plugin. You can find it here:

https://plugins.gradle.org/plugin/io.github.rmanibus.maven-settings

https://github.com/rmanibus/gradle-maven-settings-plugin
